version: "3.8"

services:
  backend:
    build: ./blog-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_PATH=/app/blog.db
    
  frontend:
    build: ./blog-frontend
    ports: 
      - "3000:80"
    networks:
      - app-network
    env_file:
      - ./blog-frontend/.env
  
networks:
  app-network:
    driver: bridge